### ISSUE TITLE
[Question] What is usage of this lib?

### ISSUE THREAD

**Issue by trsh** [vanruesc/linear-octree#1]
What are the usage cases?

**Comment by vanruesc** [comment]
This library contains a generalized version of the world octree code from [rabbit-hole](https://github.com/vanruesc/rabbit-hole/tree/master/src/octree/world) and is going to be used for [voxel data management](https://github.com/vanruesc/rabbit-hole/issues/25).

There's also a chance that more features will be added later to support moving 3D objects. The lib could then be used for things like accelerated view frustum culling and collision detection.
