### ISSUE TITLE
Cull swaps key with level

### ISSUE THREAD

**Issue by zacharygriffee** [vanruesc/linear-octree#4]
This line  
https://github.com/vanruesc/linear-octree/blob/04fb768f92db89a848bf14a250dfe658b5de3b33/src/core/Octree.ts#L207 swaps level and key.

Now chit-chat:

I been really drawn to this library as a solution to many of my use cases in a project I am working on. I've been coming back to it after trying many other methods and libraries like undirected graph and traditional sparse octrees. I am going to try and attempt to adapt this to a spherical coordinate system, as that would really hone in what I need that is no where to be found in npm-land. Thanks for the great library!

**Comment by vanruesc** [comment]
Hi, thanks for spotting that bug! I'll clean up some things and prepare a new release some time next week.

> I am going to try and attempt to adapt this to a spherical coordinate system

That sounds exciting 🚀 Let me know where to find it, if you decide to release it that is.

**Comment by zacharygriffee** [comment]
The swap also occurs in the raycaster..

https://github.com/vanruesc/linear-octree/blob/04fb768f92db89a848bf14a250dfe658b5de3b33/src/raycasting/OctreeRaycaster.ts#L55

>  Let me know where to find it, if you decide to release it that is.

I'll def post it.

**Comment by vanruesc** [comment]
Finally fixed in `linear-octree@0.2.0`. Sorry for the delay.

**Comment by zacharygriffee** [comment]
Thanks for getting around to it!
