### ISSUE TITLE
Initialization method that stays within Box3 bounds

### ISSUE THREAD

**Issue by Ctrlmonster** [vanruesc/linear-octree#7]
Hey, thanks for writing this cool library!

I'm interested in using it for a project to bake object occlusion data - [link](https://twitter.com/BrianBreiholz/status/1707449118862332268) if you're interested :)

The api looks very well designed, only one problem I'm encountering is how to initialize the octree to exactly fit a Box3 (that I've previously made to fit my scene). Maybe I'm overlooking something but all the initialization methods described in the Readme don't work for me, in the sense that the tree bounds don't stay constant when I change the levels in the Keydesign (maybe that's a bug?).

What I'm looking for is an initialization method that takes a Box3 for bounds and divides that volume up in the way described by the Keydesign. 

The following will only fit the scene bounds, if I set `level = 1`, but as soon as I increase the levels, it will no longer fit the bounds in size or position.
```js
const sceneBounds = new Box3().copy(sceneGeometry.boundingBox);
const level = 3; 
const keyDesign = new KeyDesign(level, level, level);
const octree = new Octree(sceneBounds, keyDesign);
```

Best Regards

Edit: I'm on the train right now, but I can add screenshots later on if that would help - Cheers!

**Comment by vanruesc** [comment]
Hi,

I'm not sure if I understand the problem :thinking: The octree bounds shouldn't change and the amount of levels per axis define the number of subdivisions as you'd expect.

Could you provide a failing test case to better describe how you're using the octree, what methods you're using and what results you're expecting? You can take a look at the existing unit tests for reference: https://github.com/vanruesc/linear-octree/blob/main/test/core/Octree.js

**Comment by Ctrlmonster** [comment]
Thanks for the quick Response. Yeah that's what I'd expect too. I'll compare the tests with my code tomorrow and follow up.

**Comment by Ctrlmonster** [comment]
This is how I'm initializing the octree. 

```jsx
function initOctree(mergedGeometry, level) {
  const keyDesign = new KeyDesign(level, level, level); 
  const treeBounds = new Box3();
  treeBounds.copy(mergedGeom.boundingBox);
  const octree = new Octree(treeBounds, keyDesign);
  const octreeHelper = new OctreeHelper(octree);
  scene.add(octreeHelper);
}

```
and this is the result:

`level == 1`
The bounds of the tree fit the mesh bounding box exactly (you can see z-fighting between the BoxHelper and the OctreeHelper)
![oc_level1](https://github.com/vanruesc/linear-octree/assets/33699897/c8ac9b39-f85b-47b8-adf6-736feccd84ee)

`level == 2`
![oc_level2](https://github.com/vanruesc/linear-octree/assets/33699897/7fe13be9-ec5e-4528-a909-add24c8fcacb)


`level == 3`
![oc_level3](https://github.com/vanruesc/linear-octree/assets/33699897/3189ff58-49aa-4e91-ba83-1a9ce3e7dc86)


So it seems like instead of describing the final bounds, the bounds stay that of the level 1 bounds.
I haven't come up with a test yet (can follow up in the coming days), `octree.min` and `octree.max` stay the same regardless of level, but it can't only be the octree helper that's wrong, I've been spawning voxels in each cell like this and they match the octreeHelper as well:
```js
for (const ocWrapper of octree.octants(maxAccessLvl)) {
    ocWrapper.getCenter(position);
    matrix.compose(position, quaternion, scale);
    voxels.setMatrixAt(voxelIdx, matrix);
    voxelIdx++;
}
```
--------------------------------------------------------------------------------
Two other things I've noticed:
- The octree helper is only included in the sparse-octree, not linear-octree package
- The api for getting cell sizes seems to be different than in other functions (level 0 being the smallest cell, instead of the largest - is that intended?)
```jsx
const c1 = octree.getCellSize(0, new Vector3());
const c2 = octree.getCellSize(1, new Vector3());
const c3 = octree.getCellSize(2, new Vector3());
console.log(c1, c2, c3);
 ```
 ![occ](https://github.com/vanruesc/linear-octree/assets/33699897/733fe8b6-a06b-48ae-8065-c74b7858270b)

**Comment by vanruesc** [comment]
> I've been spawning voxels in each cell like this and they match the octreeHelper as well

It's possible that you're adding data at positions that lie outside the octree. The current implementation doesn't have any safe guards for bounds checks. Are you converting the world positions of the voxels to key coordinates via `Octree.calculateKeyCoordinates`?

> octree.min and octree.max stay the same regardless of level, but it can't only be the octree helper that's wrong

The helper iterates over the keys in the octree grids. If the keys are wrong, the resulting bounds will also be wrong while the initial bounds remain the same.

> The octree helper is only included in the sparse-octree, not linear-octree package

Oh right, I'll re-export that in `linear-octree` for convenience.

> level 0 being the smallest cell, instead of the largest - is that intended?

Yes, level 0 is the smallest / most fine-grained level.

**Comment by Ctrlmonster** [comment]
> Yes, level 0 is the smallest / most fine-grained level.

That was it! It all came down to me thinking that the finest level was `maxLevel - 1` and thinking that the `OctreeHelper` was a source of truth for the tree bounds. So I basically added things out of bounds because I was using the largest, instead of the smallest cells to calculate the next voxel position. 

Maybe such an out of bounds check (as a warning) makes sense for the helper? I.e. check if the helper becomes larger than the original octree bounds expected.

Anyways, as usual the error sat in front of the monitor haha
Thanks so much for your time and help - I got it to work now :)
